name: google_docs_clone
description: A Google Docs clone built with Flutter

# The following line prevents the package from being accidentally published to
# pub.dev using pub publish. This is preferred for private packages.
publish_to: 'none'

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State management
  provider: ^6.1.1
  
  # Rich text editor
  flutter_quill: ^10.5.14
  
  # HTTP requests
  http: ^1.1.0
  
  # Storage
  shared_preferences: ^2.2.2
  
  # WebSocket
  web_socket_channel: ^2.4.0
  
  # UI
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  # fluttertoast: ^8.2.4
  
  # For handling date formats - updated to match flutter_quill requirement
  intl: ^0.19.0
  quill_delta: ^3.0.0-nullsafety.2

  device_info_plus: ^8.0.0  # Ensure the web support is available for your version
  flutter_keyboard_visibility: ^5.0.0  # Ensure web support for this package

  image_picker_for_web: ^2.1.7
  video_player_web: ^2.0.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Added for iOS and Android icons
  flutter_launcher_icons: ^0.13.1

# Flutter configuration
flutter:
  uses-material-design: true
  
  # To add assets to your application, add an assets section like this:
  assets:
    - assets/images/
  
  # Add the fonts section to define custom fonts
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Roboto-Italic.ttf
  #         style: italic